name:                hall-symbols
version:             0.1.0.3
github:              "narumij/hall-symbols"
license:             BSD3
author:              "Jun Narumi"
maintainer:          "narumij@gmail.com"
copyright:           "Jun Narumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Symmetry operations generater of Hall Symbols
category:            Chemistry

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/narumij/hall-symbols#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- parsec
- doctest

library:
  source-dirs: src

tests:
  hall-symbols-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hall-symbols
    - hspec
    - QuickCheck
    - matrix-as-xyz
